BIN = raspberry-imu-viewer

OBJECTS = \
	$(patsubst %.c,%.o,$(wildcard sensor-imu/*.c sensor-imu/orientation/*.c *.c))

CFLAGS += \
	-Wall \
	-Wextra \
	-Werror \
	-O3 \
	-I/opt/vc/include

LDFLAGS += -L/opt/vc/lib \
	-lbrcmGLESv2 \
	-lbrcmEGL \
	-lbcm_host \
	-lm

all: $(BIN)

%.o: %.c
	gcc $(CFLAGS) -c $< -o $@

$(BIN): $(OBJECTS)
	gcc $(OBJECTS) $(LDFLAGS) -o $@
